name: Test
on: push

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
      - run: yarn install --frozen-lockfile
      - run: yarn lint
      - run: yarn test
